In [1]:
import keras

Using TensorFlow backend.


In [2]:
import tensorflow as tf

In [3]:
import numpy as np

In [14]:
class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self,epoch,logs={}):
        if(logs.get('loss')<0.5):
            print("\nLoss is low so cancelling training")
            self.model.stop_training=True

In [5]:
callbacks=myCallback()

In [6]:
fashion_mnist=keras.datasets.fashion_mnist

In [7]:
(train_images,train_labels),(test_images,test_labels)=fashion_mnist.load_data()

In [8]:
model=keras.Sequential([keras.layers.Flatten(input_shape=(28,28)),
                      keras.layers.Dense(128,activation=tf.nn.relu),
                      keras.layers.Dense(10,activation=tf.nn.softmax)])

In [9]:
print(train_images)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [10]:
print(train_labels)

[9 0 0 ... 3 0 5]


In [11]:
model.compile(optimizer = 'adam',
           loss = 'sparse_categorical_crossentropy',
           metrics=['accuracy'])

In [15]:
model.fit(train_images,train_labels,epochs=10,callbacks=[callbacks])

Epoch 1/10
60000/60000 [==============================] - 4s 68us/step - loss: 0.4901 - accuracy: 0.8309
Epoch 2/10
60000/60000 [==============================] - 4s 66us/step - loss: 0.4983 - accuracy: 0.8259
Epoch 3/10
60000/60000 [==============================] - 4s 66us/step - loss: 0.4856 - accuracy: 0.8322
Epoch 4/10
60000/60000 [==============================] - 4s 66us/step - loss: 0.4834 - accuracy: 0.8332
Epoch 5/10
60000/60000 [==============================] - 4s 67us/step - loss: 0.4781 - accuracy: 0.8341
Epoch 6/10
60000/60000 [==============================] - 4s 66us/step - loss: 0.4749 - accuracy: 0.8343
Epoch 7/10
60000/60000 [==============================] - 4s 66us/step - loss: 0.4775 - accuracy: 0.8350
Epoch 8/10
60000/60000 [==============================] - 4s 70us/step - loss: 0.4794 - accuracy: 0.8339
Epoch 9/10
60000/60000 [==============================] - 4s 68us/step - loss: 0.4739 - accuracy: 0.8371
Epoch 10/10
60000/60000 [==============================

In [16]:
model.evaluate(test_images,test_labels)

10000/10000 [==============================] - 0s 34us/step


[0.563435807800293, 0.8090000152587891]