In [14]:
import keras

In [32]:
import tensorflow as tf

In [15]:
import numpy as np

In [16]:
fashion_mnist=keras.datasets.fashion_mnist

In [23]:
(train_images,train_labels),(test_images,test_labels)=fashion_mnist.load_data()

4423680/4422102 [==============================] - 32s 7us/step


In [33]:
model=keras.Sequential([keras.layers.Flatten(input_shape=(28,28)),
                      keras.layers.Dense(128,activation=tf.nn.relu),
                      keras.layers.Dense(10,activation=tf.nn.softmax)])

In [34]:
print(train_images)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [35]:
print(train_labels)

[9 0 0 ... 3 0 5]


In [48]:
model.compile(optimizer = 'adam',
           loss = 'sparse_categorical_crossentropy',
           metrics=['accuracy'])

In [50]:
model.fit(train_images,train_labels,epochs=10)

Epoch 1/10
60000/60000 [==============================] - 4s 72us/step - loss: 0.4925 - accuracy: 0.8377
Epoch 2/10
60000/60000 [==============================] - 4s 72us/step - loss: 0.4858 - accuracy: 0.8397
Epoch 3/10
60000/60000 [==============================] - 4s 72us/step - loss: 0.4790 - accuracy: 0.8427
Epoch 4/10
60000/60000 [==============================] - 4s 72us/step - loss: 0.4720 - accuracy: 0.8440
Epoch 5/10
60000/60000 [==============================] - 4s 73us/step - loss: 0.4785 - accuracy: 0.8429
Epoch 6/10
60000/60000 [==============================] - 4s 72us/step - loss: 0.4725 - accuracy: 0.8460
Epoch 7/10
60000/60000 [==============================] - 4s 72us/step - loss: 0.4752 - accuracy: 0.8454
Epoch 8/10
60000/60000 [==============================] - 4s 72us/step - loss: 0.4687 - accuracy: 0.8456
Epoch 9/10
60000/60000 [==============================] - 4s 72us/step - loss: 0.4640 - accuracy: 0.8470
Epoch 10/10
60000/60000 [==============================

In [53]:
model.evaluate(test_images,test_labels)

10000/10000 [==============================] - 0s 36us/step


[0.5906684183835983, 0.8284000158309937]